apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
  name: kn-serving-cleanup-118
spec:
  componentName: kn-serving-cleanup-118
  application: serverless-operator-138
   
  source:
    git:
      url: https://github.com/openshift-knative/serving.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-images/cleanup/Dockerfile
      revision: release-v1.18
