apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: knative-serving-storage-version-migration-release-next
spec:
  componentName: knative-serving-storage-version-migration
  application: serverless-operator-release-next
   
  source:
    git:
      url: https://github.com/openshift-knative/serving.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-images/migrate/Dockerfile
      revision: release-next
