apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-knative/serving?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "release-v1.15" 
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: serverless-operator-135
    appstudio.openshift.io/component: kn-serving-test-helloworld-115
    pipelines.appstudio.openshift.io/type: build
  name: kn-serving-test-helloworld-115-on-pull-request
  namespace: ocp-serverless-tenant
spec:
  params:
    - name: dockerfile
      value: openshift/ci-operator/knative-test-images/helloworld/Dockerfile
    - name: build-args
      value:
        - GO_BUILDER=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22
        - GO_RUNTIME=registry.access.redhat.com/ubi8/ubi-minimal
        - JAVA_BUILDER=registry.access.redhat.com/ubi8/openjdk-21
        - JAVA_RUNTIME=registry.access.redhat.com/ubi8/openjdk-21-runtime
        - VERSION=1.35.2
    - name: git-url
      value: '{{source_url}}'
    - name: hermetic
      value: "true"
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-135/kn-serving-test-helloworld:on-pr-{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
    - name: revision
      value: '{{revision}}'
  taskRunSpecs:
    - pipelineTaskName: sast-shell-check
      stepSpecs:
        - name: sast-shell-check
          computeResources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-kn-serving-test-helloworld-115
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
