apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-knative/serving?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-v1.15" 
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: serverless-operator-135
    appstudio.openshift.io/component: kn-serving-test-sidecarcontainer-115
    pipelines.appstudio.openshift.io/type: build
  name: kn-serving-test-sidecarcontainer-115-on-pull-request
  namespace: ocp-serverless-tenant
spec:
  params:
    - name: dockerfile
      value: openshift/ci-operator/knative-test-images/sidecarcontainer/Dockerfile
    - name: build-args
      value: [ VERSION=release-1.35,  GO_BUILDER=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22,  GO_RUNTIME=registry.access.redhat.com/ubi8/ubi-minimal, ]
    - name: git-url
      value: '{{source_url}}'
    - name: hermetic
      value: "true"
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-135/kn-serving-test-sidecarcontainer:on-pr-{{revision}}
    - name: revision
      value: '{{revision}}'
  pipelineRef:
    name: docker-build
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
